/**
 * Implements autostart via a marker file in the Windows Startup folder.
 */
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import type {
  AutostartContext,
  AutostartMutationReport,
  AutostartProvider,
  AutostartStatusReport,
} from '../types.js'

const STARTUP_DIR_ENV_KEY = 'MESSAGE_DROP_WINDOWS_STARTUP_DIR' as const

/** Marker / shortcut-like file created by `message-drop autostart enable` on Windows. */
export const WINDOWS_AUTOSTART_MARKER_FILENAME =
  'message-drop-autostart.cmd' as const

const MARKER_BODY = [
  '@echo off',
  'REM message-drop-autostart — generated by `message-drop autostart enable`',
  'message-drop start',
  '',
].join('\r\n')

function resolveStartupDirectory(ctx: AutostartContext): string {
  const override = ctx.env[STARTUP_DIR_ENV_KEY]
  if (override !== undefined && override !== '') {
    return override
  }
  const appData = ctx.env.APPDATA
  if (appData !== undefined && appData !== '') {
    return join(
      appData,
      'Microsoft',
      'Windows',
      'Start Menu',
      'Programs',
      'Startup',
    )
  }
  return join(
    ctx.homedir,
    'AppData',
    'Roaming',
    'Microsoft',
    'Windows',
    'Start Menu',
    'Programs',
    'Startup',
  )
}

function markerPath(ctx: AutostartContext): string {
  return join(resolveStartupDirectory(ctx), WINDOWS_AUTOSTART_MARKER_FILENAME)
}

export function createWindowsStartupProvider(): AutostartProvider {
  return {
    id: 'windows-startup',

    async status(ctx: AutostartContext): Promise<AutostartStatusReport> {
      const path = markerPath(ctx)
      if (!existsSync(path)) {
        return {
          providerId: 'windows-startup',
          state: 'not-installed',
          lines: [
            `Windows Startup: autostart is disabled (no marker at ${path}).`,
            `Run: message-drop autostart enable`,
          ],
          isError: false,
        }
      }
      return {
        providerId: 'windows-startup',
        state: 'installed-active',
        lines: [
          `Windows Startup: autostart is enabled (marker at ${path}).`,
          `Run: message-drop autostart disable`,
        ],
        isError: false,
      }
    },

    async enable(ctx: AutostartContext): Promise<AutostartMutationReport> {
      const dir = resolveStartupDirectory(ctx)
      const path = markerPath(ctx)
      try {
        mkdirSync(dir, { recursive: true })
        if (existsSync(path)) {
          return {
            providerId: 'windows-startup',
            lines: [
              `Windows Startup: autostart already enabled (marker exists at ${path}).`,
            ],
            isError: false,
          }
        }
        writeFileSync(path, MARKER_BODY, 'utf8')
        return {
          providerId: 'windows-startup',
          lines: [
            `Windows Startup: wrote startup marker at ${path}.`,
            `Run: message-drop autostart disable to remove it.`,
          ],
          isError: false,
        }
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err)
        return {
          providerId: 'windows-startup',
          lines: [
            `Windows Startup: failed to enable autostart under ${dirname(path)}.`,
            msg,
          ],
          isError: true,
        }
      }
    },

    async disable(ctx: AutostartContext): Promise<AutostartMutationReport> {
      const path = markerPath(ctx)
      try {
        if (!existsSync(path)) {
          return {
            providerId: 'windows-startup',
            lines: [
              `Windows Startup: autostart already disabled (no marker at ${path}).`,
            ],
            isError: false,
          }
        }
        unlinkSync(path)
        return {
          providerId: 'windows-startup',
          lines: [
            `Windows Startup: removed startup marker at ${path}.`,
          ],
          isError: false,
        }
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err)
        return {
          providerId: 'windows-startup',
          lines: [
            `Windows Startup: failed to disable autostart (marker at ${path}).`,
            msg,
          ],
          isError: true,
        }
      }
    },
  }
}
